#%RAML 1.0
title: Upload file API
baseUri: http://localhost:4015
mediaType: multipart/form-data

/upload/{id}:
    post:
        description: Creates a file
    body:
        properties:
            file:
                description: The file to be upload
                required: true
                type: file
            expiring_date:
                description: Expiring date
                required: true
                type: string
            shared:
                description: Shared email list
                type: string[]