#%RAML 1.0
title: Upload file API
baseUri: http://localhost:4015
mediaType: multipart/form-data

/upload/{id}:
    post:
        description: Creates a file
        body:
            properties:
                file: file
                expiring_date: string
