upload-db:
  build: ./db_server
  ports:
    - "3010:5984"
upload-ms:
  build: ./upload_ms
  environment:
      DB_PORT: '5984'
      DB_URL: 'upload-db'
      DB_NAME: 'blinkbox_files'
      HOST_URL: '0.0.0.0'
      HOST_PORT: '4015'
  ports:
    - "4015:4015"
  links:
    - upload-db
